//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enFrenzyHack.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("enFrenzyHack.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {
        ///  &quot;executable&quot;: &quot;csgo.exe&quot;,
        ///  &quot;filename&quot;: &quot;csgo&quot;,
        ///  &quot;signatures&quot;: [
        ///    {
        ///      &quot;name&quot;: &quot;dwClientState&quot;,
        ///      &quot;extra&quot;: 0,
        ///      &quot;relative&quot;: true,
        ///      &quot;module&quot;: &quot;engine.dll&quot;,
        ///      &quot;offsets&quot;: [
        ///        1
        ///      ],
        ///      &quot;pattern&quot;: &quot;A1 ? ? ? ? 33 D2 6A 00 6A 00 33 C9 89 B0&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: &quot;dwClientState_GetLocalPlayer&quot;,
        ///      &quot;extra&quot;: 0,
        ///      &quot;relative&quot;: false,
        ///      &quot;module&quot;: &quot;engine.dll&quot;,
        ///      &quot;offsets&quot;: [
        ///        2
        ///      ],
        ///      &quot;pattern&quot;: &quot;8B 80 ? ? ? ? 40 C3&quot;
        ///    },
        ///    {
        ///      &quot;name&quot;: [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string config {
            get {
                return ResourceManager.GetString("config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] hazedumper {
            get {
                object obj = ResourceManager.GetObject("hazedumper", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        internal static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NotifierImage {
            get {
                object obj = ResourceManager.GetObject("NotifierImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
